version: '3.1'

services:

  lprometheus:
    image: prom/prometheus
    container_name: local_prometheus
    ports:
      - "9090:9090"
#    volumes:
#      - ./prometheus-data:/etc/prometheus     
    restart: always
    networks:
      - atul-net


  lgrafana:
    image: grafana/grafana
    container_name: local_grafana   
    ports:
      - "3000:3000"  
    depends_on:
      - lprometheus
    # volumes:
    #   - ./grafana-data:/var/lib/grafana   
    restart: always
    networks:
      - atul-net

  luptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: local_uptime_kuma
    volumes:
      - ./data:/app/data
    ports:
      - 3001:3001

    depends_on:
      - lprometheus
      - lgrafana
    restart: unless-stopped

    networks:
      - atul-net
      
networks:
  atul-net:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:




