global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "lprometheus"
    static_configs:
      - targets: ["localhost:9090", "lprometheus:9090"]

  - job_name: "lnode_exporter"
    static_configs:
      - targets: ["lnode_exporter:9100"]
      
 # - job_name: 'luptime-kuma'
  #   static_configs:
  #     - targets: ["localhost:9090", "luptime-kuma:3001"] 

  # - job_name: 'lgrafana'
  #   static_configs:
  #     - targets: ["localhost:9090", "lgrafana:3000"] 
